// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBrowser.Data
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class DataBrowserDbContext : System.Data.Entity.DbContext, IDataBrowserDbContext
    {
        public System.Data.Entity.DbSet<DatabaseConnection> DatabaseConnections { get; set; } // DatabaseConnection
        public System.Data.Entity.DbSet<FieldConfiguration> FieldConfigurations { get; set; } // FieldConfiguration
        public System.Data.Entity.DbSet<FieldMappingConfiguration> FieldMappingConfigurations { get; set; } // FieldMappingConfiguration
        public System.Data.Entity.DbSet<SchemaVersion> SchemaVersions { get; set; } // SchemaVersions
        public System.Data.Entity.DbSet<TableConfiguration> TableConfigurations { get; set; } // TableConfiguration
        public System.Data.Entity.DbSet<User> Users { get; set; } // User

        static DataBrowserDbContext()
        {
            System.Data.Entity.Database.SetInitializer<DataBrowserDbContext>(null);
        }

        public DataBrowserDbContext()
            : base("Name=DataBrowserEntities")
        {
            InitializePartial();
        }

        public DataBrowserDbContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }
		
        public DataBrowserDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public DataBrowserDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public DataBrowserDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }
		
        protected override void Dispose(bool disposing)
        {
            DisposePartial(disposing);
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            //modelBuilder.Configurations.Add(new DatabaseConnectionConfiguration());
            //modelBuilder.Configurations.Add(new FieldConfigurationConfiguration());
            //modelBuilder.Configurations.Add(new FieldMappingConfigurationConfiguration());
            //modelBuilder.Configurations.Add(new SchemaVersionConfiguration());
            //modelBuilder.Configurations.Add(new TableConfigurationConfiguration());
            //modelBuilder.Configurations.Add(new UserConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            //modelBuilder.Configurations.Add(new DatabaseConnectionConfiguration(schema));
            //modelBuilder.Configurations.Add(new FieldConfigurationConfiguration(schema));
            //modelBuilder.Configurations.Add(new FieldMappingConfigurationConfiguration(schema));
            //modelBuilder.Configurations.Add(new SchemaVersionConfiguration(schema));
            //modelBuilder.Configurations.Add(new TableConfigurationConfiguration(schema));
            //modelBuilder.Configurations.Add(new UserConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void DisposePartial(bool disposing);
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
