// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBrowser.Data
{

    // TableConfiguration
    [Table("TableConfiguration", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public partial class TableConfiguration
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_TableConfiguration", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        [Column(@"DataKey", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Data key")]
        public string DataKey { get; set; } // DataKey (length: 50)

        [Column(@"IsTable", Order = 4, TypeName = "bit")]
        [Display(Name = "Is table")]
        public bool? IsTable { get; set; } // IsTable

        [Column(@"IsView", Order = 5, TypeName = "bit")]
        [Display(Name = "Is view")]
        public bool? IsView { get; set; } // IsView

        [Column(@"MasterTableName", Order = 6, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Master table name")]
        public string MasterTableName { get; set; } // MasterTableName (length: 50)

        [Column(@"ConnectionId", Order = 7, TypeName = "int")]
        [Display(Name = "Connection ID")]
        public int? ConnectionId { get; set; } // ConnectionId

        // Reverse navigation

        /// <summary>
        /// Child FieldConfigurations where [FieldConfiguration].[TableConfigId] point to this entity (FK_FieldConfiguration_TableConfiguration)
        /// </summary>
        //public virtual System.Collections.Generic.ICollection<FieldConfiguration> FieldConfigurations { get; set; } = new System.Collections.Generic.List<FieldConfiguration>(); // FieldConfiguration.FK_FieldConfiguration_TableConfiguration

        // Foreign keys

        /// <summary>
        /// Parent DataBaseConnection pointed by [TableConfiguration].([ConnectionId]) (FK_TableConfiguration_DataBaseConnection)
        /// </summary>
        [ForeignKey("ConnectionId")] public virtual DataBaseConnection DataBaseConnection { get; set; } // FK_TableConfiguration_DataBaseConnection
    }

}
// </auto-generated>
